version: '3.1'

services:
server:
  build:
    context: .
    target: prod
  environment:
    NODE_ENV: production
    MYSQL_HOST: mysql
    REDIS_HOST: redis
  ports:
    - 3000:3000
  depends_on:
    - mysql
    - redis

  mysql:
    image: mysql
    restart: always
    ports:
      - '${MYSQL_DESKTOP_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - persitence_volume:/var/lib/mysql

  redis:
    image: redis/redis-stack-server
    restart: always
    ports:
      - '${REDIS_DESKTOP_PORT}:${REDIS_PORT}'

volumes:
  persitence_volume:
